# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('art', '0001_initial'), ('art', '0002_auto_20170503_2243')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('year_begin', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('bio', models.TextField()),
                ('nationality', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True)),
                ('classification', models.TextField(blank=True)),
                ('department', models.TextField(blank=True)),
                ('culture', models.TextField(blank=True)),
                ('medium', models.TextField(blank=True)),
                ('created', models.DateField(null=True)),
                ('museum_id', models.URLField(null=True)),
                ('museum_link', models.URLField(blank=True)),
                ('museum_name', models.TextField(blank=True)),
                ('public_domain', models.BooleanField()),
            ],
        ),
    ]
