# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('year_begin', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('bio', models.TextField()),
                ('nationality', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True)),
                ('classification', models.TextField(blank=True)),
                ('department', models.TextField(blank=True)),
                ('culture', models.TextField(blank=True)),
                ('medium', models.TextField(blank=True)),
                ('created', models.DateField(null=True)),
                ('museum_id', models.URLField()),
                ('museum_link', models.URLField()),
                ('museum_name', models.TextField()),
                ('public_domain', models.BooleanField()),
                ('image_url_small', models.URLField(null=True)),
                ('image_url_large', models.URLField(null=True)),
            ],
        ),
    ]
