# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='museum_id',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='public_domain',
            field=models.BooleanField(default=False),
        ),
    ]
