# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_artwork_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artists',
            field=models.ManyToManyField(related_name='artworks', to='art.Artist'),
        ),
    ]
